stages:
  - test
  - verify
  - integration

variables:
  ErrorActionPreference: STOP

Test:
  stage: test
  tags:
    - windows
  script:
    - powershell.exe -NoProfile -ExecutionPolicy Bypass -File .\run-tests.ps1
  except:
    - master

Verification:
  stage: verify
  tags:
    - windows
  script:
    - powershell.exe -NoProfile -ExecutionPolicy Bypass -File .\run-tests.ps1
  only:
    - master

Integration:
  stage: integration
  tags:
    - windows
  script:
    - powershell.exe -NoProfile -ExecutionPolicy Bypass -File .\run-integration-tests.ps1
  rules:
    - if: '$CI_COMMIT_REF_PROTECTED == "true"'
      when: manual
      allow_failure: true
    - when: never
